replicas: 1

image:
  registry: docker.io
  repository: grafana/grafana
  tag: "11.4.0"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  pathType: Prefix

  hosts:
    - grafana-example.local
  tls: []
  #  - secretName: cert-secret
  #    hosts:
  #      - grafana-example.local

nodeSelector: {}

adminUser: admin
adminPassword: Abc123

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

rbac:
  create: false

serviceAccount:
  create: false
testFramework:
  enabled: false
  
createConfigmap: true

automountServiceAccountToken: false
